spring.application.name=bff
server.port=8081
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/5497f70a-565c-40b7-92c7-b62049f8638f/v2.0
backend.service.url=http://localhost:8080/api
logging.level.org.springframework.web: DEBUG
spring.datasource.url=jdbc:oracle:thin:@healzjhb0k6m53n7_high?TNS_ADMIN=./Wallet_HEALZJHB0K6M53N7
spring.datasource.username=ADMIN    
spring.datasource.password=Tardigrado13.
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

spring.kafka.bootstrap-servers=localhost:29092,localhost:39092,localhost:49092
spring.kafka.consumer.group-id=grupo-alertas
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.topic.alertas=alertas
